[package]
name = "live_chat_service"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.3"
prost = "0.13.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1"
futures = "0.3"

[build-dependencies]
tonic-build = "0.12.3"
